/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a map_adaptor org.hondson.demo.Map.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "map_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MapAdaptor
 */

MapAdaptor::MapAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MapAdaptor::~MapAdaptor()
{
    // destructor
}

void MapAdaptor::onClicked()
{
    // handle method call org.hondson.demo.Map.onClicked
    QMetaObject::invokeMethod(parent(), "onClicked");
}

void MapAdaptor::onDoubleClicked()
{
    // handle method call org.hondson.demo.Map.onDoubleClicked
    QMetaObject::invokeMethod(parent(), "onDoubleClicked");
}

void MapAdaptor::pan(int in0, int in1)
{
    // handle method call org.hondson.demo.Map.pan
    QMetaObject::invokeMethod(parent(), "pan", Q_ARG(int, in0), Q_ARG(int, in1));
}

void MapAdaptor::swipe(const QString &in0, int in1)
{
    // handle method call org.hondson.demo.Map.swipe
    QMetaObject::invokeMethod(parent(), "swipe", Q_ARG(QString, in0), Q_ARG(int, in1));
}

